name: Moderation
version: 1.0
author: Redwoub
main: fr.redwoub.moderation.Main
commands:
  mod:
    permission: moderation.mod
    permission-message: §cVous n'avez pas la permisson d'executer cette commande.
  report:
  freeze:
    permission: moderation.freeze
    permission-message: §cVous n'avez pas la permisson d'executer cette commande.
  unfreeze:
    permission: moderation.unfreeze
    permission-message: §cVous n'avez pas la permisson d'executer cette commande.